### ISSUE TITLE
Database Relation

### ISSUE THREAD

**Issue by Qasammiii** [ITUTE/portal#1]
There is no database Present in the Project Directory. So I cant understand the Relation of tables in according to the Given Queries Please Help Me Out from this

**Comment by rahup97** [comment]
This was made specifically for our organisation, but you can tweak the database and the queries as per your need. 
[portal.xml.zip](https://github.com/ITUTE/portal/files/1540286/portal.xml.zip)
this is the portal database that you can import from phpmyadmin.

**Comment by utkarshv43** [comment]
I am sorry we cannot share as its private stuff.

**Comment by Qasammiii** [comment]
I need this to understand my personal Use.. But as You mention its Private So its Ok Thanks for response.. Best of Luck for Project.
Have a Blessed Day
